// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/assets/images/bg-dark.png"
    | "/assets/images/bg.jpg"
    | "/assets/images/ext_icon_dark.png"
    | "/assets/images/ext_icon.png"
    | "/assets/images/iitkgp-logo.svg"
    | "/assets/sprite.svg"
    | "/content-scripts/content.js"
    | "/icon/icon-128.png"
    | "/icon/icon-16.png"
    | "/icon/icon-32.png"
    | "/icon/icon-48.png"
    | "/icon/icon-placeholder.png"
    | "/popup.html"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
